# Generated by Django 4.0.1 on 2022-02-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo'),
            preserve_default=False,
        ),
    ]
