# Generated by Django 4.0.1 on 2022-03-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biscuit',
            name='flavour',
            field=models.CharField(choices=[('sweet', 'sweet'), ('salty', 'salty'), ('cream', 'cream')], max_length=30),
        ),
    ]
